<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AssemblyName>Presentation.WebApi</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.12" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.11"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.1">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Domain.Repository\Domain.Repository.csproj" />
      <ProjectReference Include="..\Presentation.Core\Presentation.Core.csproj" />
      <ProjectReference Include="..\Service.Contracts\Service.Contracts.csproj" />
      <ProjectReference Include="..\Service.UseCases\Service.UseCases.csproj" />
      <ProjectReference Include="..\Shared.Logger\Shared.Logger.csproj" />
      <ProjectReference Include="..\Shared.Validators\Shared.Validators.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="wwwroot\images\" />
    </ItemGroup>

</Project>
